### ISSUE TITLE
运行项目闪退 android.view.InflateException: Binary XML file line #3: Error inflating class android.support.v7.widget.CardView

### ISSUE THREAD

**Issue by mark2L** [leoleohan/RefreshDemo#1]
android:foreground="?android:attr/selectableItemBackgroundBorderless"  在API21以下运行直接崩掉了

**Comment by VeerHan** [comment]
谢谢你的提醒。该行代码的确最低兼容API21，但是我没有想到它会在API21以下直接崩掉，之后我会删除该行代码。再次感谢。
